# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 'master'  # Use the sha / tag you want to point at
    hooks:
    -   id: flake8
        args: []
