---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trawler-certificate
  namespace: apic
spec:
  dnsNames:
    - trawler.apic.svc.cluster.local
  duration: 17520h0m0s
  # Update with your appropriate cert issuer
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ingress-cluster-issuer
  renewBefore: 720h0m0s
  secretName: trawler-certificate
  usages:
    - digital signature
    - key encipherment
