# Example configuration file
prometheus:
  port: 63512
  enabled: true
logging:
  level: info
nets:
  apiconnect:
    enabled: true
    namespace: apic-namespace
  analytics:
    enabled: true
    namespace: analytics-namespace
  certificates:
    enabled: true
    frequency: 600        
  datapower:
    enabled: true
    username: admin
    namespace: gateway-namespace
    api_tests:
      enabled: false
      apis:
        - name: testapi
          path: /porg/catalog/test
          method: get
          headers: {}
  manager:
    enabled: true
    process_org_metrics: false
    namespace: manager-namespace