# Example configuration file
prometheus:
  port: 63512 
  enabled: true
nets:
  datapower:
    enabled: false
    username: admin
    namespace: apic-gateway
  manager:
    enabled: true
    username: admin
    namespace: apic-management
  analytics:
    enabled: true
    namespace: apic-analytics
