apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: trawler
  files:
  - config.yaml
resources:
- deployment.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
# Uncomment secret.yaml if you have set passwords in it
# - secret.yaml
#  Uncomment the following if you are using prometheus-operator
# - service.yaml
# - servicemonitor.yaml

namespace: apic-monitoring
