apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: trawler
  name: trawler
spec:
  endpoints:
  - port: web
    path: /
    interval: 30s
    scheme: https
    tlsConfig:
      ca:
        secret:
          key: ca.crt
          name: trawler-certificate
      cert:
        secret:
          key: tls.crt
          name: trawler-certificate
      insecureSkipVerify: false
      keySecret:
        key: tls.key
        name: trawler-certificate
      serverName: trawler.apic.svc.cluster.local
  selector:
    matchLabels:
      app: trawler
