apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: trawler
  name: trawler
spec:
  endpoints:
  - port: metrics
    path: /
  jobLabel: trawler
  selector:
    matchLabels:
      app: trawler
