{
 "title": "Trawler Sample",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(apiconnect_build_info,clusterName)"
    }
   },
   {
    "name": "Gateway",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(apiconnect_gatewayclusters_status,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"text-align: right\"><img src=\"http://cdn.mcauto-images-production.sendgrid.net/32631292384e2be3/64a808dd-6024-4f4c-a38b-643c3c2c7e2d/57x57.png\" alt=\"API Connect Logo\"></p>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "max by(version) (apiconnect_build_info{clusterName=\"$Cluster\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "API Calls (last hour)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (analytics_apicalls_lasthour_2xx{})",
     "legendFormat": "2xx"
    },
    {
     "expr": "max (analytics_apicalls_lasthour_3xx{})",
     "legendFormat": "3xx"
    },
    {
     "expr": "max (analytics_apicalls_lasthour_4xx{})",
     "legendFormat": "4xx"
    },
    {
     "expr": "max (analytics_apicalls_lasthour_5xx{})",
     "legendFormat": "5xx "
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "max by(component) (consumption_health_status{clusterName=\"$Cluster\"})",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Subsystem Readiness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "apiconnect_managementclusters_status{type=\"Ready\", clusterName=\"$Cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "expr": "apiconnect_portalclusters_status{type=\"Ready\",clusterName=\"$Cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "expr": "apiconnect_gatewayclusters_status{type=\"Ready\",clusterName=\"$Cluster\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "API Manager Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Provider Orgs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_provider_orgs)" }
   ]
  },
  {
   "title": "API Manager Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_users)" }
   ]
  },
  {
   "title": "Catalogs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_catalogs)" }
   ]
  },
  {
   "title": "Spaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_spaces)" }
   ]
  },
  {
   "title": "Products",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_products)" }
   ]
  },
  {
   "title": "APIs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_apis)" }
   ]
  },
  {
   "title": "Outstanding Queued Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "max(manager_gateway_processing_outstanding_queued_events)",
     "legendFormat": "Outstanding Queued Events"
    },
    {
     "expr": "max(manager_gateway_processing_outstanding_sent_events)",
     "legendFormat": "Outstanding Sent Events"
    }
   ]
  },
  {
   "title": "Draft Products",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_draft_products)" }
   ]
  },
  {
   "title": "Draft APIs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_draft_apis)" }
   ]
  },
  {
   "title": "Consumer Orgs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_consumer_orgs)" }
   ]
  },
  {
   "title": "Consumer Apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_consumer_apps)" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(manager_subscriptions)" }
   ]
  },
  { "title": "Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_cluster_status{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_active_primary_shards_total{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_unassigned_shards_total{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_relocating_shards_total{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Analytics Shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "analytics_active_primary_shards_total",
     "legendFormat": "primary shards"
    },
    { "expr": "analytics_active_shards_total", "legendFormat": "active shards" },
    {
     "expr": "analytics_relocating_shards_total",
     "legendFormat": "relocating shards"
    },
    {
     "expr": "analytics_unassigned_shards_total",
     "legendFormat": "unassigned shards"
    },
    {
     "expr": "analytics_initializing_shards_total",
     "legendFormat": "initializing shards"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_nodes_total{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_active_shards_total{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(analytics_initializing_shards_total{clusterName=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "datapower_invoke_api_echo_status_total",
       "legendFormat": "{{clusterName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway - $Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "Gateway",
   "collapsed": true,
   "panels": [
    {
     "title": "Cached document count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(exported_pod) (datapower_documentcache_apiconnect_DocCount{exported_namespace=\"$Gateway\"})",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    },
    {
     "title": "Cached document size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "max by(exported_pod) (datapower_documentcache_apiconnect_CacheSizeKiB{exported_namespace=\"$Gateway\"})",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    },
    {
     "title": "API Collections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "max by(exported_pod) (datapower_APICollection_total{exported_namespace=\"$Gateway\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Definitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "targets": [
      {
       "expr": "max by(exported_pod) (datapower_APIDefinition_total{exported_namespace=\"$Gateway\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "log events processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "max by(exported_pod) (rate(datapower_logtarget_stdout_EventsProcessed{exported_namespace=\"$Gateway\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "log events dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
     "targets": [
      {
       "expr": "max by(exported_pod) (rate(datapower_logtarget_stdout_EventsDropped{exported_namespace=\"$Gateway\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP: established",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "max(datapower_tcp_established_total{exported_namespace=\"$Gateway\"}) by (exported_pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP: close wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
     "targets": [
      {
       "expr": "max(datapower_tcp_close_wait_total{exported_namespace=\"$Gateway\"}) by (exported_pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway (v5c)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "WSM Records Seen",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "max(datapower_wsm_RecordsSeen) by(exported_pod)     ",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    },
    {
     "title": "WSM Records Lost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "targets": [
      {
       "expr": "max(datapower_wsm_RecordsLost) by(exported_pod)     ",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    },
    {
     "title": "WSM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "max(datapower_wsm_MemoryUsedKB) by(exported_pod)     ",
       "legendFormat": "{{exported_pod}}"
      }
     ]
    }
   ]
  }
 ]
}